SELECT * FROM CUSTOMER;
SELECT * FROM PASSENGERS_ON_FLIGHTS;
SELECT * FROM ROUTES;
SELECT * FROM TICKET_DETAILS;

-- 2. Create ROUTE_DETAILS Table.
CREATE TABLE ROUTE_DETAILS
( ROUTE_ID INT PRIMARY KEY, 
FLIGHT_NUM INT CHECK(FLIGHT_NUM > 0), 
ORIGIN_AIRPORT VARCHAR(10),
DESTINATION_AIRPORT VARCHAR(10),
AIRCRAFT_ID VARCHAR (10),
DISTANCE_MILES INT CHECK(DISTANCE_MILES>0));
